# Generated by Django 4.2.6 on 2023-10-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('department_id', models.CharField(choices=[('computerscience', 'Computer Science'), ('biologyscience', 'Biology Science'), ('commerce', 'Commerce'), ('humanities', 'Humanities'), ('journalism', 'Journalism')], max_length=15)),
                ('course_id', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('enquiry', 'Enquiry'), ('order', 'Place Order'), ('return', 'Return')], max_length=7)),
                ('materials_provide', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
